server:
  port: 8012

netconfig:
  tcp_port: 1001
  udp_port: 1002

task:
  cron: "0/30 * * * * ?"

logging:
  pattern:
    file: "%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  file:
    name: logs/server.log
  level:
    root: info